apiVersion: v1
kind: PersistentVolume
metadata:
  name: hlfpv
spec:
  storageClassName: standard
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /opt/share
    server: 129.108.4.65
   
